### ISSUE TITLE
Why is it not being built?

### ISSUE THREAD

**Issue by Dliwk** [RomashkaGang/kernel_xiaomi_platina#1]
*I cannot build it*
*I cannot build it*
*I cannot build it*
*I cannot build it*
*I cannot build it*

**Comment by Ivan1874** [comment]
@Dliwk Эм

**Comment by Ivan1874** [comment]
@Dliwk Ты дебил?

**Comment by Ivan1874** [comment]
@Dliwk What steps did you performed in order to build it?

**Comment by Dliwk** [comment]
@Ivan1874 чо ты пристал?
